### ISSUE TITLE
uncapitalized tracklists

### ISSUE THREAD

**Issue by jgchk** [jgchk/betterRYM#22]

**Comment by sc113** [comment]
Some cases need to be fixed:
"be" - should be capitalized
"[alpha remix]" - square brackets shouldn't count as the first letter, 2nd letter after [ should be capitalised. same about last word in square brackets - it should be "Remix]"
"the" should be capitalzed when it's the last word
(the [the - (in most cases) should be capitalzed when it's the first word in brackets
